# fly.toml app configuration file generated for noviious-backend on 2026-03-29T11:27:45+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noviious-backend'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  DJANGO_SETTINGS_MODULE = 'config.settings.production'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/api/v1/health/'

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
