# Generated by Django 4.2.10 on 2026-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "otp_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "code"], name="otp_codes_email_a86f0d_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="otp_codes_expires_348c2d_idx"
                    ),
                ],
            },
        ),
    ]
