# Generated by Django 5.0.1 on 2026-03-28 14:56

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimage_image_alter_productimage_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.products.models.product_image_upload_path,
            ),
        ),
    ]
